# Generated by Django 5.0.7 on 2024-08-04 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relays', '0003_alter_relay_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='relay_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
